version: '3'
services:
  llm-broker:
    build:
      context: .
    container_name: llm-broker
    image: llm-broker:latest
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - DEFAULT_MODEL=$DEFAULT_MODEL